### ISSUE TITLE
Failed to build with Qt 6.4.1

### ISSUE THREAD

**Issue by iahung** [davidbannon/libqt6pas#6]
```
src/qabstracteventdispatcher_c.cpp: In function 'bool QAbstractEventDispatcher_registerEventNotifier(QAbstractEventDispatcherH, QWinEventNotifierH)':
src/qabstracteventdispatcher_c.cpp:97:61: error: 'class QAbstractEventDispatcher' has no member named 'registerEventNotifier'; did you mean 'registerSocketNotifier'?
   97 |         return (bool) ((QAbstractEventDispatcher *)handle)->registerEventNotifier((QWinEventNotifier*)notifier);
      |                                                             ^~~~~~~~~~~~~~~~~~~~~
      |                                                             registerSocketNotifier
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:2738: tmp/qabstracteventdispatcher_c.o] Error 1
```

**Comment by davidbannon** [comment]
iahung, you have not told us what OS or even what make system you have used. Are you using a linux distro that supplied the Qt6 you are using ? Or did you install it yourself, direct from Qt ?  What version of c++ you are using ?

It appears to me to be a bug in the cbinding but I really don't know and without the above information, its really just guessing.

If there is a problem, it needs to be reported on the Lazarus issues page, not here, the only bug reports I can accept here are about the pre-built libraries I provide here for convenience of users. The c++ code here is never ahead and usually exactly the same as that in the Lazarus repository.

Thanks for your interest.

Davo
